export const TYPING_TEXTS = [
  "La velocidad de escritura no es simplemente mover los dedos con rapidez sobre el teclado, sino encontrar ese ritmo perfecto entre la mente y las manos que permite alcanzar una fluidez total y natural. Los mejores mecanografos del mundo han perfeccionado esta habilidad a traves de miles de horas de practica dedicada, desarrollando una memoria muscular que les permite escribir sin siquiera mirar las teclas. El secreto esta en la constancia y la paciencia, entendiendo que cada error es una oportunidad de aprendizaje.",

  "Cada tecla presionada con precision te acerca mas a la victoria en este desafio de mecanografia. No se trata simplemente de correr contra el tiempo, sino de fluir sin errores a traves del texto, manteniendo un ritmo constante y controlado. Los expertos recomiendan practicar al menos treinta minutos diarios para ver mejoras significativas en la velocidad y precision. La clave esta en no sacrificar la exactitud por la rapidez, ya que los errores cuestan mas tiempo del que ahorras escribiendo rapido.",

  "El arte de escribir rapido combina multiples elementos que van mas alla de la simple mecanica de presionar teclas. Requiere una practica constante y disciplinada, una concentracion profunda que te permita anticipar las palabras, y una postura ergonomica que prevenga lesiones por esfuerzo repetitivo. Los mejores mecanografos del mundo hacen que esta habilidad parezca facil y completamente natural, pero detras hay anos de dedicacion y miles de palabras escritas. La ergonomia del espacio de trabajo tambien juega un papel fundamental en el rendimiento.",

  "Programar es como escribir poesia con logica pura y estructurada. Cada linea de codigo cuenta una historia que las maquinas pueden entender, interpretar y ejecutar con precision milimetrica. Los desarrolladores de software pasan horas frente al teclado, transformando ideas abstractas en aplicaciones funcionales que millones de personas utilizan cada dia. Dominar la escritura rapida no solo aumenta la productividad, sino que permite mantener el flujo de pensamiento sin interrupciones molestas mientras se codifica. La eficiencia en el teclado se traduce directamente en mejor codigo.",

  "Los grandes escritores y periodistas no nacieron escribiendo a velocidades impresionantes. Cada uno de ellos practico incansablemente cada dia hasta que sus dedos se movian solos por el teclado, casi sin necesidad de pensar conscientemente en cada letra. Esta automatizacion del proceso de escritura libera la mente para concentrarse en lo verdaderamente importante: las ideas, la creatividad, y la estructura del mensaje que quieren transmitir. El teclado se convierte en una extension natural del pensamiento, una herramienta invisible que traduce pensamientos en palabras escritas instantaneamente.",

  "La tecnologia avanza a pasos agigantados en el mundo moderno y dominar el teclado se ha convertido en una habilidad absolutamente fundamental para desenvolverse con exito en el entorno digital contemporaneo. Desde estudiantes hasta profesionales experimentados, todos se benefician enormemente de poder escribir con fluidez y sin errores. Las estadisticas muestran que una persona promedio puede aumentar su productividad en un cuarenta por ciento simplemente mejorando su velocidad de escritura. Este es el momento perfecto para invertir en desarrollar esta habilidad que te acompanara toda la vida profesional.",

  "Respirar profundamente antes de comenzar cualquier prueba de escritura ayuda significativamente a mantener la calma y la concentracion necesarias. Los nervios y la ansiedad son los peores enemigos de la velocidad al momento de escribir bajo presion. Los atletas de esports y los competidores profesionales de mecanografia utilizan tecnicas de respiracion y visualizacion para alcanzar estados de concentracion optima. Mantener una postura relajada pero alerta, con los hombros hacia atras y los pies firmemente apoyados en el suelo, contribuye enormemente al rendimiento.",

  "Mil palabras por minuto no significan absolutamente nada si cada una de ellas contiene errores tipograficos o de ortografia. La precision siempre debe ir primero que la velocidad pura, ya que un texto lleno de errores requiere tiempo adicional de correccion que elimina cualquier ventaja ganada. Los expertos recomiendan mantener una tasa de precision minima del noventa y cinco por ciento antes de intentar aumentar la velocidad. Este enfoque garantiza un progreso sostenible y evita desarrollar malos habitos de escritura que son dificiles de corregir posteriormente.",

  "El teclado moderno tiene sus raices en la maquina de escribir inventada en el siglo diecinueve, y su disposicion QWERTY fue disenada especificamente para evitar que las barras de metal se trabaran durante la escritura rapida. Aunque hoy usamos teclados digitales que no tienen esta limitacion fisica, el diseno ha perdurado por mas de ciento cincuenta anos debido a la familiaridad universal. Algunos layouts alternativos como Dvorak prometen mayor eficiencia, pero la adopcion masiva del QWERTY hace que sea la opcion mas practica para la mayoria de usuarios.",

  "La competencia de mecanografia profesional es un deporte real con campeonatos mundiales donde los mejores escriben a velocidades que superan las doscientas palabras por minuto con precision casi perfecta. Estos atletas del teclado entrenan durante horas cada dia, perfeccionando su tecnica y desarrollando una resistencia mental extraordinaria. Sus dedos se mueven con una velocidad y precision que parece casi sobrehumana para el observador casual. El record mundial actual supera las trescientas palabras por minuto, una hazana que requiere anos de entrenamiento dedicado."
];

export function getRandomText(): string {
  return TYPING_TEXTS[Math.floor(Math.random() * TYPING_TEXTS.length)];
}
