export const TYPING_TEXTS = [
  "La velocidad de escritura no es simplemente mover los dedos con rapidez sobre el teclado, sino encontrar ese ritmo perfecto entre la mente y las manos que permite alcanzar una fluidez total y natural. Los mejores mecanografos del mundo han perfeccionado esta habilidad a traves de miles de horas de practica dedicada, desarrollando una memoria muscular que les permite escribir sin siquiera mirar las teclas. El secreto esta en la constancia y la paciencia, entendiendo que cada error es una oportunidad de aprendizaje valiosa que nos acerca mas a la maestria total de este arte.",

  "Cada tecla presionada con precision te acerca mas a la victoria en este desafio de mecanografia. No se trata simplemente de correr contra el tiempo, sino de fluir sin errores a traves del texto, manteniendo un ritmo constante y controlado. Los expertos recomiendan practicar al menos treinta minutos diarios para ver mejoras significativas en la velocidad y precision. La clave esta en no sacrificar la exactitud por la rapidez, ya que los errores cuestan mas tiempo del que ahorras escribiendo rapido y descuidado.",

  "El arte de escribir rapido combina multiples elementos que van mas alla de la simple mecanica de presionar teclas. Requiere una practica constante y disciplinada, una concentracion profunda que te permita anticipar las palabras, y una postura ergonomica que prevenga lesiones por esfuerzo repetitivo. Los mejores mecanografos del mundo hacen que esta habilidad parezca facil y completamente natural, pero detras hay anos de dedicacion intensa y miles de palabras escritas diariamente hasta automatizar cada movimiento de los dedos.",

  "Programar es como escribir poesia con logica pura y estructurada. Cada linea de codigo cuenta una historia que las maquinas pueden entender, interpretar y ejecutar con precision milimetrica. Los desarrolladores de software pasan horas frente al teclado, transformando ideas abstractas en aplicaciones funcionales que millones de personas utilizan cada dia. Dominar la escritura rapida no solo aumenta la productividad, sino que permite mantener el flujo de pensamiento sin interrupciones mientras se codifica y se resuelven problemas complejos.",

  "Los grandes escritores y periodistas no nacieron escribiendo a velocidades impresionantes. Cada uno de ellos practico incansablemente cada dia hasta que sus dedos se movian solos por el teclado, casi sin necesidad de pensar conscientemente en cada letra. Esta automatizacion del proceso de escritura libera la mente para concentrarse en lo verdaderamente importante: las ideas, la creatividad, y la estructura del mensaje que quieren transmitir al mundo. El teclado se convierte en una extension completamente natural del pensamiento humano.",

  "La tecnologia avanza a pasos agigantados en el mundo moderno y dominar el teclado se ha convertido en una habilidad absolutamente fundamental para desenvolverse con exito en el entorno digital contemporaneo. Desde estudiantes hasta profesionales experimentados, todos se benefician enormemente de poder escribir con fluidez y sin errores constantes. Las estadisticas muestran que una persona promedio puede aumentar su productividad en un cuarenta por ciento simplemente mejorando su velocidad de escritura con practica regular.",

  "Respirar profundamente antes de comenzar cualquier prueba de escritura ayuda significativamente a mantener la calma y la concentracion necesarias para rendir al maximo nivel. Los nervios y la ansiedad son los peores enemigos de la velocidad al momento de escribir bajo presion intensa. Los atletas de esports y los competidores profesionales de mecanografia utilizan tecnicas de respiracion y visualizacion mental para alcanzar estados de concentracion optima antes de cada competicion importante y decisiva.",

  "Mil palabras por minuto no significan absolutamente nada si cada una de ellas contiene errores tipograficos o de ortografia graves. La precision siempre debe ir primero que la velocidad pura, ya que un texto lleno de errores requiere tiempo adicional de correccion que elimina cualquier ventaja ganada. Los expertos recomiendan mantener una tasa de precision minima del noventa y cinco por ciento antes de intentar aumentar la velocidad al siguiente nivel de rendimiento profesional y competitivo.",

  "El teclado moderno tiene sus raices en la maquina de escribir inventada en el siglo diecinueve, y su disposicion QWERTY fue disenada especificamente para evitar que las barras de metal se trabaran durante la escritura rapida y fluida. Aunque hoy usamos teclados digitales que no tienen esta limitacion fisica, el diseno ha perdurado por mas de ciento cincuenta anos debido a la familiaridad universal de millones de usuarios alrededor del mundo que aprendieron con este sistema estandar.",

  "La competencia de mecanografia profesional es un deporte real con campeonatos mundiales donde los mejores escriben a velocidades que superan las doscientas palabras por minuto con precision casi perfecta e impresionante. Estos atletas del teclado entrenan durante horas cada dia, perfeccionando su tecnica y desarrollando una resistencia mental extraordinaria que les permite mantener la concentracion durante periodos prolongados. Sus dedos se mueven con una velocidad que parece casi sobrehumana para cualquier observador casual que los contempla.",

  "La memoria muscular es el fundamento mas importante de la mecanografia experta y profesional. Cuando los dedos aprenden exactamente donde se encuentra cada tecla del teclado sin necesidad de buscar visualmente, la velocidad se incrementa de manera exponencial y sostenida. Este proceso de automatizacion profunda requiere semanas de practica deliberada y enfocada antes de comenzar a manifestarse de forma consistente. Una vez alcanzado este estado de dominio, escribir se convierte en un acto casi inconsciente y completamente fluido que permite enfocarse en el contenido.",

  "Los teclados mecanicos han experimentado un resurgimiento extraordinario en popularidad entre los entusiastas de la escritura rapida y los programadores profesionales de todo el mundo. La retroalimentacion tactil y sonora que proporcionan mejora significativamente la precision al escribir, ya que el mecanografo puede sentir con claridad cuando cada tecla ha sido activada correctamente. Existen diferentes tipos de switches mecanicos, cada uno con caracteristicas propias de resistencia y sonido que se adaptan a distintos estilos y preferencias personales de escritura.",

  "La posicion correcta de los dedos sobre el teclado es fundamental para alcanzar velocidades altas de manera sostenida y sin fatiga. Los dedos indices deben descansar sobre las teclas F y J, que tienen una marca tactil especial para orientarse sin necesidad de mirar. Desde esta posicion inicial conocida como posicion base, cada dedo tiene asignadas teclas especificas que debe cubrir de manera natural y eficiente. Romper este habito fundamental de posicionamiento correcto es uno de los errores mas costosos que cometen los principiantes en mecanografia.",

  "Escribir rapido y con precision no es un talento innato con el que algunas personas nacen afortunadamente. Es una habilidad completamente aprendida que cualquier persona dedicada puede desarrollar con la practica adecuada y constante a lo largo del tiempo. Los ninos que aprenden mecanografia desde temprana edad desarrollan una ventaja significativa que los acompana durante toda su vida academica y profesional. Sin embargo, nunca es demasiado tarde para comenzar a mejorar esta habilidad tan valiosa en el mundo digital moderno.",

  "La concentracion total es el estado mental que separa a los mecanografos ordinarios de los verdaderamente extraordinarios y competitivos. Cuando la mente divaga o se distrae por cualquier razon, los dedos cometen errores que interrumpen el flujo natural de la escritura y reducen la velocidad global. Los practicantes avanzados aprenden a entrar en un estado de flujo donde el tiempo parece detenerse y los dedos se mueven de manera completamente automatica sobre el teclado. Alcanzar este estado requiere practica deliberada, paciencia inquebrantable y una dedicacion constante al perfeccionamiento."
];

export function getTextByIndex(index: number): string {
  return TYPING_TEXTS[index % TYPING_TEXTS.length];
}
